---
- name: Destroy Cluster with IBM Cloud Managed Istio
  hosts: localhost
  collections:
  - ibm.cloudcollection
  tasks:
    - name: Fetch the variables from var file
      include_vars:
        file: vars.yml

    
    - name: Destroy Cluster
      ibm_container_cluster:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        default_pool_size: 3
        wait_till: "OneWorkerNodeReady"
        name: "{{ prefix }}-cluster"
        entitlement: "{{ entitlement }}"
        kube_version: "{{ kube_version }}"
        public_vlan_id: "{{ publicvlan.id }}"
        private_vlan_id: "{{ privatevlan.id }}"
        resource_group_id: "{{ rgid }}"
        force_delete_storage: True
        pod_subnet: "{{ pod_subnet }}"
        service_subnet: "{{ service_subnet }}"
        public_service_endpoint: "{{ enable_public_se }}"
        private_service_endpoint: "{{ enable_private_se }}"
        datacenter: "{{ zone1 }}"
        state: absent
        id: "{{ cluster.id | default(omit) }}"
        machine_type: "bx2.4x16"
        gateway_enabled: "{{ gateway_enabled }}"
      register: cluster_create_output
      when: cluster is defined

    - name: Destroy private VLAN
      ibm_network_vlan:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        iaas_classic_username: "{{ sl_username }}"
        iaas_classic_api_key: "{{ sl_key }}"
        region: "{{ region }}"
        datacenter: "{{ zone1 }}"
        router_hostname: "bcr01a.{{ zone1 }}"
        type: "private"
        name: "{{ prefix }}-private"
        state: absent
        id: "{{ privatevlan.id | default(omit) }}"
      register: private_vlan_create_output
      when: privatevlan is defined
    

    
    - name: Destroy public VLAN
      ibm_network_vlan:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        iaas_classic_username: "{{ sl_username }}"
        iaas_classic_api_key: "{{ sl_key }}"
        region: "{{ region }}"
        datacenter: "{{ zone1 }}"
        router_hostname: "fcr01a.{{ zone1 }}"
        type: "public"
        name: "{{ prefix }}-public"
        state: absent
        id: "{{ publicvlan.id | default(omit) }}"
      register: public_vlan_create_output
      when: publicvlan is defined
  
    
